apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkZXZvcHNlYXN5bGVhcm5pbmciLCJwYXNzd29yZCI6ImRja3JfcGF0X2VfbjIxNF9BNl9mWDFwOHE5bk5GbXNJUWt2QSIsImVtYWlsIjoiaW5mb0BkZXZvcHNlYXN5bGVhcm5pbmcuY29tIiwiYXV0aCI6IlpHVjJiM0J6WldGemVXeGxZWEp1YVc1bk9tUmphM0pmY0dGMFgyVmZiakl4TkY5Qk5sOW1XREZ3T0hFNWJrNUdiWE5KVVd0MlFRPT0ifX19
kind: Secret
metadata:
  name: {{ .Values.containerPullSecrets.name }} # s5emile-registrykey
type: {{ .Values.containerPullSecrets.type }} #kubernetes.io/dockerconfigjson






# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.containerPullSecrets.name }}
# data:
#   .dockerconfigjson: ZGV2b3BzZWFzeWxlYXJuaW5nOmRja3JfcGF0X2VfbjIxNF9BNl9mWDFwOHE5bk5GbXNJUWt2QQ==
# type: {{ .Values.containerPullSecrets.type }}