apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_SERVICE_HOST: cmVkMTIz  # Base64-encoded value of "redis"
  REDIS_MASTER_PASSWORD: czVlbWlsZQ==  # Base64-encoded value of "s5emile"
  REDIS_PASSWORD: czVlbWlsZQ==  # Base64-encoded value of "s5emile"
  REDIS_PORT: NjM3OQ==  # Base64-encoded value of "6379"
