apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-product
type: Opaque
data:
  POSTGRES_PASSWORD: cDVlbWlsZQ==  # Base64-encoded value of "s5emile"
  POSTGRES_USER: cG9zdGdyZXNz
  POSTGRES_HOST: cG9zdGdyZXNxbC1oYS1wb3N0Z3Jlc3Fs
  POSTGRES_DB: cDVlbWlsZQ==
